### PR TITLE
feat: Make _get_access_token async

### PR DESCRIPTION
**Pull request by bigbugboy**
feat _get_access_token & not use a thread pool

### CODE REVIEW

**Comment by akalex** [comment]
@bigbugboy Please bump up the version and add a record in `CHANGELOG.md`.

**Comment by bigbugboy** [comment]
ok, done

**Comment by akalex** [comment]
@bigbugboy some linters failed, could you please take a look at them a fix. Thank you in advance.

**Comment by bigbugboy** [comment]
fix the linters failed and feat the test based on this new _get_access_token, please review

**Comment by akalex** [comment]
@bigbugboy please apply black recommendations as it's still complaining.

**Review by akalex — APPROVED** [review]
LGTM

**Pull request merged**
