### PR TITLE
Http2

### PR DESCRIPTION
**Pull request by cyberbudy**
Add #85 support

### CODE REVIEW

**Comment by cyberbudy** [comment]
I'll appreciate any guidance what I've done wrong :)

**Comment by akalex** [comment]
Hey @Gera3dartist @ndmytro,
Could either of you take a look at this and help @cyberbudy with pushing it forward? Thank you in advance.

**Review by Gera3dartist — DISMISSED** [review]
lgtm

**Comment by Gera3dartist** [comment]
@cyberbudy once conflicts  in `poetry.lock` are fixed,  we can move it further

**Comment by cyberbudy** [comment]
There is a problem with setuptools on 3.12

**Comment by akalex** [comment]
@cyberbudy please pull latest changes into your branch and restart the pipeline. Thank you

**Comment by akalex** [comment]
@cyberbudy I fixed pipeline, so we should be good to proceed further.
cc: @Gera3dartist @ndmytro

**Comment by akalex** [comment]
lgtm

**Review by Gera3dartist — APPROVED** [review]
LGTM

**Pull request merged**
