### PR TITLE
feat: add channel_id to android notification params

### PR DESCRIPTION
**Pull request by festinuz**
In accordance with firebase cloud messaging spec:
https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages#AndroidNotification

### CODE REVIEW

**Comment by akalex** [comment]
@festinuz Could you please do a couple of things:

- bump up the version
- update CHANGE with the information about the changes

**Review by akalex — COMMENTED** [review]
@festinuz Could you please do a couple of things:

-     bump up the version
-     update CHANGES.md with the information about the changes

**Comment by festinuz** [comment]
Sure thing, done!

**Review by akalex — APPROVED** [review]
LGTM

**Pull request merged**
